/**
 * CARBON'S OWN REGISTRY — the carbon partition's declaration + registration file (2026-10-03).
 *
 * THE WALL, as always (PLANS.AGENT/multiple-catalogs.md §10): this file is the carbon partition's
 * own — the app's shared/tag-registry.ts is the prompt-composer catalogue's file, and a second
 * catalogue never writes into it.
 *
 * WHAT IS DIFFERENT ABOUT THIS ONE — AND IT IS THE SHAPE THE OWNER ASKED FOR: the elements are
 * NOT copied source. They are CARBON'S OWN published Lit components (IBM's
 * @carbon/web-components package): *"those design systems were already prepared for lit"* is
 * exactly right, so this registry IMPORTS THE VENDOR'S OWN MODULES — each registers its cds-* tag
 * and ships its own compiled styles — and there is nothing to adapt and nothing to drift; an
 * upstream release is an npm update. (Kor and AgnosticUI remain the copied-source class; both
 * classes are legal under the wall, and this one is what a manifest-shipping package makes cheap.)
 *
 * THE TWO HALVES, as every system has: the RESOLUTION half is the partition's own registry.json
 * (name→tag, GENERATED by scripts/prepare_design_system.mjs from Carbon's own Custom Elements
 * Manifest); the DECLARATION half is this file. The catalogue
 * (wireframe-lab/catalogs/carbon/catalog.json, generated from the same manifest) is the AUTHORITY
 * for the full measured prop sets — these declarations carry the same measured props, and a prop
 * the manifest could not type was LEFT OUT by the generation (its printed report names them).
 *
 * THE THEME — THE LESSON FROM THE NIGHT KOR LOOKED "HIDEOUS": a design system's look IS its
 * tokens, and without them every component renders as a skeleton. Carbon ships its styles with
 * its components; the tokens (--cds-*, namespaced — nothing of this app collides) come from
 * @carbon/styles, imported once here. This import is not optional decoration; it is half the
 * package.
 *
 * WHAT CARBON'S COMPONENTS EXPECT, IN ONE NOTE: a cds-button's LABEL and a cds-card's CONTENTS
 * ride slots as CONTENT, not attributes — the compile's contract carries the attributes it can
 * write; content arrives when placement learns to carry text (the same honest limit the record
 * carries for every slot-fed component).
 */
import type { TagDefinition } from '@/shared/tag-registry';
import '@carbon/styles/css/styles.min.css';
import '@carbon/web-components/es/components/button/index.js';
import '@carbon/web-components/es/components/card/index.js';
import '@carbon/web-components/es/components/checkbox/index.js';
import '@carbon/web-components/es/components/select/index.js';
import '@carbon/web-components/es/components/text-input/index.js';
import '@carbon/web-components/es/components/textarea/index.js';

export const SYSTEM = 'carbon';

export const COMPONENTS: Record<string, TagDefinition> = {
  'cds-button': {
    tag: 'cds-button',
    surface: 'composer',
    column: 'middle',
    description: "CARBON'S OWN BUTTON \u2014 IBM's @carbon/web-components package used AS-IS (the registry imports the vendor's module; nothing copied, nothing to drift). Its LABEL rides the default slot as content.",
    props: {
      'autofocus': { type: 'boolean', optional: true },
      'batch-action': { type: 'boolean', optional: true },
      'danger-description': { type: 'string', optional: true },
      'disabled': { type: 'boolean', optional: true },
      'download': { type: 'string', optional: true },
      'has-main-content': { type: 'boolean', optional: true },
      'href': { type: 'string', optional: true },
      'hreflang': { type: 'string', optional: true },
      'isExpressive': { type: 'boolean', optional: true },
      'isSelected': { type: 'boolean', optional: true },
      'kind': { type: 'string', optional: true },
      'link-role': { type: 'string', optional: true },
      'openTooltip': { type: 'boolean', optional: true },
      'ping': { type: 'string', optional: true },
      'rel': { type: 'string', optional: true },
      'size': { type: 'string', optional: true },
      'tab-index': { type: 'number', optional: true },
      'target': { type: 'string', optional: true },
      'tooltip-alignment': { type: 'string', optional: true },
      'tooltip-position': { type: 'string', optional: true },
      'tooltip-text': { type: 'string', optional: true },
      'type': { type: 'string', optional: true },
    },
    events: [],
    constraints: [
      'CARBON\'S OWN COMPONENT \u2014 its look, its styles and its a11y are IBM\'s; do not restyle it here; the catalogue owns it',
    ],
  },
  'cds-card': {
    tag: 'cds-card',
    surface: 'composer',
    column: 'middle',
    description: "CARBON'S OWN CARD \u2014 the room's CONTAINER for Carbon layouts ('Always create a container first'): its contents ride the default slot as children.",
    props: {
      'clickable': { type: 'boolean', optional: true },
      'density': { type: 'string', optional: true },
      'horizontal': { type: 'boolean', optional: true },
      'media-position': { type: 'string', optional: true },
      'disabled': { type: 'boolean', optional: true },
      'download': { type: 'string', optional: true },
      'href': { type: 'string', optional: true },
      'hreflang': { type: 'string', optional: true },
      'inline': { type: 'boolean', optional: true },
      'link-role': { type: 'string', optional: true },
      'ping': { type: 'string', optional: true },
      'rel': { type: 'string', optional: true },
      'size': { type: 'string', optional: true },
      'target': { type: 'string', optional: true },
      'type': { type: 'string', optional: true },
      'visited': { type: 'boolean', optional: true },
    },
    events: [],
    constraints: [
      'CARBON\'S OWN COMPONENT \u2014 its look, its styles and its a11y are IBM\'s; do not restyle it here; the catalogue owns it',
      'A CONTAINER: its contents ride slots (default, decorator, footer-icon) \u2014 a draft node\'s `children` mount into the default slot',
    ],
  },
  'cds-checkbox': {
    tag: 'cds-checkbox',
    surface: 'composer',
    column: 'middle',
    description: "CARBON'S OWN CHECKBOX \u2014 label-text is the visible label; checked/indeterminate are its states.",
    props: {
      'checked': { type: 'boolean', optional: true },
      'data-table': { type: 'boolean', optional: true },
      'disabled': { type: 'boolean', optional: true },
      'hide-checkbox': { type: 'boolean', optional: true },
      'hide-label': { type: 'boolean', optional: true },
      'id': { type: 'string', optional: true },
      'indeterminate': { type: 'boolean', optional: true },
      'label-text': { type: 'string', optional: true },
      'name': { type: 'string', optional: true },
      'readonly': { type: 'boolean', optional: true },
      'invalid': { type: 'boolean', optional: true },
      'title': { type: 'string', optional: true },
      'value': { type: 'string', optional: true },
      'warn': { type: 'boolean', optional: true },
      'warn-text': { type: 'boolean', optional: true },
    },
    events: [],
    constraints: [
      'CARBON\'S OWN COMPONENT \u2014 its look, its styles and its a11y are IBM\'s; do not restyle it here; the catalogue owns it',
    ],
  },
  'cds-select': {
    tag: 'cds-select',
    surface: 'composer',
    column: 'middle',
    description: "CARBON'S OWN SELECT \u2014 label-text is the visible label; its options ride the default slot (placement does not carry option children yet).",
    props: {
      'isFluid': { type: 'boolean', optional: true },
      'autofocus': { type: 'boolean', optional: true },
      'disabled': { type: 'boolean', optional: true },
      'helper-text': { type: 'string', optional: true },
      'hide-label': { type: 'boolean', optional: true },
      'id': { type: 'string', optional: true },
      'invalid': { type: 'boolean', optional: true },
      'invalid-text': { type: 'string', optional: true },
      'warn': { type: 'boolean', optional: true },
      'warn-text': { type: 'string', optional: true },
      'label-text': { type: 'string', optional: true },
      'label-styles-disable': { type: 'boolean', optional: true },
      'inline': { type: 'boolean', optional: true },
      'multiple': { type: 'boolean', optional: true },
      'name': { type: 'string', optional: true },
      'pattern': { type: 'string', optional: true },
      'placeholder': { type: 'string', optional: true },
      'readonly': { type: 'boolean', optional: true },
      'required': { type: 'boolean', optional: true },
      'required-validity-message': { type: 'string', optional: true },
      'selectedIndex': { type: 'number', optional: true },
      'value': { type: 'string', optional: true },
    },
    events: [],
    constraints: [
      'CARBON\'S OWN COMPONENT \u2014 its look, its styles and its a11y are IBM\'s; do not restyle it here; the catalogue owns it',
    ],
  },
  'cds-text-input': {
    tag: 'cds-text-input',
    surface: 'composer',
    column: 'middle',
    description: "CARBON'S OWN TEXT INPUT \u2014 label-text is the visible label; value/placeholder/required/invalid are the working states.",
    props: {
      'autocomplete': { type: 'string', optional: true },
      'autofocus': { type: 'boolean', optional: true },
      'disabled': { type: 'boolean', optional: true },
      'enable-counter': { type: 'boolean', optional: true },
      'helper-text': { type: 'string', optional: true },
      'invalid-text': { type: 'string', optional: true },
      'warn': { type: 'boolean', optional: true },
      'warn-text': { type: 'string', optional: true },
      'hide-label': { type: 'boolean', optional: true },
      'label': { type: 'string', optional: true },
      'name': { type: 'string', optional: true },
      'pattern': { type: 'string', optional: true },
      'placeholder': { type: 'string', optional: true },
      'readonly': { type: 'boolean', optional: true },
      'hidePasswordLabel': { type: 'string', optional: true },
      'showPasswordLabel': { type: 'string', optional: true },
      'show-password-visibility-toggle': { type: 'boolean', optional: true },
      'size': { type: 'string', optional: true },
      'isFluid': { type: 'boolean', optional: true },
      'inline': { type: 'boolean', optional: true },
      'tooltipAlignment': { type: 'string', optional: true },
      'tooltipDirection': { type: 'string', optional: true },
      'type': { type: 'string', optional: true },
      'invalid': { type: 'boolean', optional: true },
      'required': { type: 'boolean', optional: true },
      'required-validity-message': { type: 'string', optional: true },
      'validity-message': { type: 'string', optional: true },
      'value': { type: 'string', optional: true },
    },
    events: [],
    constraints: [
      'CARBON\'S OWN COMPONENT \u2014 its look, its styles and its a11y are IBM\'s; do not restyle it here; the catalogue owns it',
    ],
  },
  'cds-textarea': {
    tag: 'cds-textarea',
    surface: 'composer',
    column: 'middle',
    description: "CARBON'S OWN TEXTAREA \u2014 label-text is the visible label; rows sizes it; its value rides as the value attribute.",
    props: {
      'counter-mode': { type: 'string', optional: true },
      'id': { type: 'string', optional: true },
      'rows': { type: 'number', optional: true },
      'autocomplete': { type: 'string', optional: true },
      'autofocus': { type: 'boolean', optional: true },
      'disabled': { type: 'boolean', optional: true },
      'enable-counter': { type: 'boolean', optional: true },
      'helper-text': { type: 'string', optional: true },
      'invalid-text': { type: 'string', optional: true },
      'warn': { type: 'boolean', optional: true },
      'warn-text': { type: 'string', optional: true },
      'hide-label': { type: 'boolean', optional: true },
      'label': { type: 'string', optional: true },
      'name': { type: 'string', optional: true },
      'pattern': { type: 'string', optional: true },
      'placeholder': { type: 'string', optional: true },
      'readonly': { type: 'boolean', optional: true },
      'hidePasswordLabel': { type: 'string', optional: true },
      'showPasswordLabel': { type: 'string', optional: true },
      'show-password-visibility-toggle': { type: 'boolean', optional: true },
      'isFluid': { type: 'boolean', optional: true },
      'inline': { type: 'boolean', optional: true },
      'invalid': { type: 'boolean', optional: true },
      'required': { type: 'boolean', optional: true },
      'required-validity-message': { type: 'string', optional: true },
      'validity-message': { type: 'string', optional: true },
      'value': { type: 'string', optional: true },
    },
    events: [],
    constraints: [
      'CARBON\'S OWN COMPONENT \u2014 its look, its styles and its a11y are IBM\'s; do not restyle it here; the catalogue owns it',
    ],
  },
};
